// 1xxx – cereals / porridge / dough / breakfast mixes
// 2xxx – fruits
// 3xxx – vegetables
// 4xxx – side dishes / rice / pasta / legumes
// 5xxx – meat / fish / processed meats
// 6xxx – dairy / eggs / cheeses
// 7xxx – bread / crispbread / tortilla
// 8xxx – fats / nuts / sweeteners
// 9xxx – spices / seasonings / herbs

export type Ingredient = {
  id: number;
  name: string;
  kcal: number; // per 100 g
  proteins: number; // per 100 g
  carbohydrates: number; // per 100 g
  fats: number; // per 100 g
};

// Ingredients database (values per 100 g)
export const ingredientsDb: Ingredient[] = [
  // ==================================================
  // 1xxx — cereals, porridge, dough, breakfast mixes
  // ==================================================
  {
    id: 1001,
    name: 'ovesné vločky',
    kcal: 372,
    proteins: 13,
    carbohydrates: 60,
    fats: 7,
  },
  {
    id: 1002,
    name: 'celozrnná mouka',
    kcal: 340,
    proteins: 13,
    carbohydrates: 72,
    fats: 2,
  },
  {
    id: 1003,
    name: 'pšeničná mouka',
    kcal: 364,
    proteins: 10,
    carbohydrates: 76,
    fats: 1,
  },
  {
    id: 1004,
    name: 'strouhanka',
    kcal: 351,
    proteins: 13,
    carbohydrates: 71,
    fats: 4,
  },
  {
    id: 1005,
    name: 'mák',
    kcal: 525,
    proteins: 18,
    carbohydrates: 28,
    fats: 42,
  },
  {
    id: 1010,
    name: 'granola / müsli (granule)',
    kcal: 450,
    proteins: 10,
    carbohydrates: 64,
    fats: 15,
  },

  // ==================================================
  // 2xxx — fruits
  // ==================================================
  {
    id: 2001,
    name: 'jablko',
    kcal: 52,
    proteins: 0.3,
    carbohydrates: 14,
    fats: 0.2,
  },
  {
    id: 2002,
    name: 'hruška',
    kcal: 57,
    proteins: 0.4,
    carbohydrates: 15,
    fats: 0.1,
  },
  {
    id: 2003,
    name: 'banán',
    kcal: 89,
    proteins: 1.1,
    carbohydrates: 23,
    fats: 0.3,
  },
  {
    id: 2004,
    name: 'mandarinka',
    kcal: 53,
    proteins: 0.8,
    carbohydrates: 13,
    fats: 0.3,
  },
  {
    id: 2005,
    name: 'borůvky',
    kcal: 57,
    proteins: 0.7,
    carbohydrates: 14.5,
    fats: 0.3,
  },
  {
    id: 2006,
    name: 'lesní ovoce',
    kcal: 45,
    proteins: 1,
    carbohydrates: 10,
    fats: 0.3,
  },
  {
    id: 2007,
    name: 'meruňky',
    kcal: 48,
    proteins: 1.4,
    carbohydrates: 11,
    fats: 0.4,
  },
  {
    id: 2008,
    name: 'mandarinková šťáva',
    kcal: 43,
    proteins: 0.6,
    carbohydrates: 10,
    fats: 0.2,
  },
  {
    id: 2009,
    name: 'švestky',
    kcal: 46,
    proteins: 0.7,
    carbohydrates: 11.4,
    fats: 0.3,
  },
  {
    id: 2010,
    name: 'avokádo',
    kcal: 160,
    proteins: 2.0,
    carbohydrates: 8.5,
    fats: 14.7,
  },
  {
    id: 2011,
    name: 'pomeranč',
    kcal: 47,
    proteins: 0.9,
    carbohydrates: 12,
    fats: 0.1,
  },

  // ==================================================
  // 3xxx — vegetables
  // ==================================================
  {
    id: 3001,
    name: 'rajče',
    kcal: 18,
    proteins: 0.9,
    carbohydrates: 3.9,
    fats: 0.2,
  },
  {
    id: 3002,
    name: 'okurka',
    kcal: 15,
    proteins: 0.7,
    carbohydrates: 3.6,
    fats: 0.1,
  },
  {
    id: 3003,
    name: 'paprika',
    kcal: 31,
    proteins: 1,
    carbohydrates: 6,
    fats: 0.3,
  },
  {
    id: 3004,
    name: 'cibule',
    kcal: 40,
    proteins: 1.1,
    carbohydrates: 9.3,
    fats: 0.1,
  },
  {
    id: 3005,
    name: 'česnek',
    kcal: 149,
    proteins: 6.4,
    carbohydrates: 33,
    fats: 0.5,
  },
  {
    id: 3006,
    name: 'brokolice',
    kcal: 34,
    proteins: 2.8,
    carbohydrates: 7,
    fats: 0.4,
  },
  {
    id: 3007,
    name: 'květák',
    kcal: 25,
    proteins: 1.9,
    carbohydrates: 5,
    fats: 0.3,
  },
  {
    id: 3008,
    name: 'červená řepa',
    kcal: 43,
    proteins: 1.6,
    carbohydrates: 10,
    fats: 0.2,
  },
  {
    id: 3009,
    name: 'listový salát',
    kcal: 15,
    proteins: 1.5,
    carbohydrates: 2,
    fats: 0.2,
  },
  {
    id: 3010,
    name: 'zeleninový mix',
    kcal: 30,
    proteins: 1.5,
    carbohydrates: 5,
    fats: 0.3,
  },
  {
    id: 3011,
    name: 'bílé zelí',
    kcal: 25,
    proteins: 1.3,
    carbohydrates: 5.8,
    fats: 0.1,
  },
  {
    id: 3012,
    name: 'rajčatové pyré / passata',
    kcal: 30,
    proteins: 1.5,
    carbohydrates: 6,
    fats: 0.2,
  },
  {
    id: 3013,
    name: 'kyselá okurka',
    kcal: 12,
    proteins: 0.3,
    carbohydrates: 2.2,
    fats: 0.2,
  },
  {
    id: 3014,
    name: 'žampiony (houby)',
    kcal: 22,
    proteins: 3.1,
    carbohydrates: 3.3,
    fats: 0.3,
  },
  {
    id: 3015,
    name: 'rajská omáčka',
    kcal: 65,
    proteins: 1.5,
    carbohydrates: 12,
    fats: 1.5,
  },
  {
    id: 3016,
    name: 'hříbky (houby)',
    kcal: 34,
    proteins: 3.7,
    carbohydrates: 6.0,
    fats: 0.4,
  },
  {
    id: 3017,
    name: 'špenát',
    kcal: 23,
    proteins: 2.9,
    carbohydrates: 3.6,
    fats: 0.4,
  },
  {
    id: 3018,
    name: 'paprika (lusk)',
    kcal: 31,
    proteins: 1.0,
    carbohydrates: 6.0,
    fats: 0.3,
  },

  // ==================================================
  // 4xxx — side dishes, rice, pasta, legumes
  // ==================================================
  {
    id: 4001,
    name: 'brambory vařené',
    kcal: 87,
    proteins: 2,
    carbohydrates: 20,
    fats: 0.1,
  },
  {
    id: 4002,
    name: 'batáty',
    kcal: 86,
    proteins: 1.6,
    carbohydrates: 20,
    fats: 0.1,
  },
  {
    id: 4003,
    name: 'rýže vařená',
    kcal: 130,
    proteins: 2.7,
    carbohydrates: 28,
    fats: 0.3,
  },
  {
    id: 4004,
    name: 'divoká rýže',
    kcal: 101,
    proteins: 4,
    carbohydrates: 21,
    fats: 0.3,
  },
  {
    id: 4005,
    name: 'celozrnné těstoviny vařené',
    kcal: 124,
    proteins: 5,
    carbohydrates: 26,
    fats: 1.2,
  },
  {
    id: 4006,
    name: 'bulgur vařený',
    kcal: 83,
    proteins: 3.1,
    carbohydrates: 18.6,
    fats: 0.2,
  },
  {
    id: 4007,
    name: 'čočka vařená',
    kcal: 116,
    proteins: 9,
    carbohydrates: 20,
    fats: 0.4,
  },
  {
    id: 4008,
    name: 'cizrna vařená',
    kcal: 164,
    proteins: 9,
    carbohydrates: 27,
    fats: 2.6,
  },
  {
    id: 4009,
    name: 'fazole vařené (kidney)',
    kcal: 127,
    proteins: 8.7,
    carbohydrates: 22.8,
    fats: 0.5,
  },
  {
    id: 4010,
    name: 'rýžové nudle',
    kcal: 109,
    proteins: 1.8,
    carbohydrates: 24.9,
    fats: 0.2,
  },

  // ==================================================
  // 5xxx — meat, fish, processed meats
  // ==================================================
  {
    id: 5001,
    name: 'kuřecí prsa',
    kcal: 110,
    proteins: 23,
    carbohydrates: 0,
    fats: 1.5,
  },
  {
    id: 5002,
    name: 'krůtí prsa',
    kcal: 110,
    proteins: 24,
    carbohydrates: 0,
    fats: 1,
  },
  {
    id: 5003,
    name: 'hovězí libové',
    kcal: 160,
    proteins: 26,
    carbohydrates: 0,
    fats: 6,
  },
  {
    id: 5004,
    name: 'vepřové libové',
    kcal: 165,
    proteins: 25,
    carbohydrates: 0,
    fats: 7,
  },
  {
    id: 5005,
    name: 'losos',
    kcal: 208,
    proteins: 20,
    carbohydrates: 0,
    fats: 13,
  },
  {
    id: 5006,
    name: 'tuňák ve vlastní šťávě',
    kcal: 116,
    proteins: 26,
    carbohydrates: 0,
    fats: 1,
  },
  {
    id: 5007,
    name: 'šunka',
    kcal: 110,
    proteins: 19,
    carbohydrates: 1,
    fats: 3,
  },
  {
    id: 5008,
    name: 'frankfurtský párek',
    kcal: 280,
    proteins: 12,
    carbohydrates: 2,
    fats: 24,
  },
  {
    id: 5009,
    name: 'bílá ryba (treska)',
    kcal: 82,
    proteins: 18,
    carbohydrates: 0,
    fats: 0.7,
  },
  {
    id: 5010,
    name: 'parmská šunka',
    kcal: 270,
    proteins: 26,
    carbohydrates: 0.5,
    fats: 18,
  },

  // ==================================================
  // 6xxx — dairy products, eggs, cheeses
  // ==================================================
  {
    id: 6001,
    name: 'polotučný tvaroh',
    kcal: 90,
    proteins: 16,
    carbohydrates: 3,
    fats: 2,
  },
  {
    id: 6002,
    name: 'tvaroh',
    kcal: 90,
    proteins: 16,
    carbohydrates: 3,
    fats: 2,
  },
  {
    id: 6003,
    name: 'řecký jogurt 2%',
    kcal: 73,
    proteins: 9,
    carbohydrates: 4,
    fats: 2,
  },
  {
    id: 6004,
    name: 'jogurt bílý',
    kcal: 60,
    proteins: 5,
    carbohydrates: 4,
    fats: 3,
  },
  {
    id: 6005,
    name: 'mléko 1.5%',
    kcal: 47,
    proteins: 3.4,
    carbohydrates: 4.8,
    fats: 1.5,
  },
  {
    id: 6006,
    name: 'vejce',
    kcal: 143,
    proteins: 13,
    carbohydrates: 1.1,
    fats: 9.5,
  },
  {
    id: 6007,
    name: 'cottage',
    kcal: 98,
    proteins: 11,
    carbohydrates: 3.5,
    fats: 4.3,
  },
  {
    id: 6008,
    name: 'eidam 30%',
    kcal: 260,
    proteins: 28,
    carbohydrates: 1.5,
    fats: 16,
  },
  {
    id: 6009,
    name: 'mozzarella',
    kcal: 250,
    proteins: 18,
    carbohydrates: 2,
    fats: 19,
  },
  {
    id: 6010,
    name: 'hermelín',
    kcal: 330,
    proteins: 19,
    carbohydrates: 1,
    fats: 28,
  },
  {
    id: 6011,
    name: 'balkánský sýr',
    kcal: 260,
    proteins: 14,
    carbohydrates: 2,
    fats: 21,
  },
  {
    id: 6012,
    name: 'parmazán',
    kcal: 431,
    proteins: 38,
    carbohydrates: 4,
    fats: 29,
  },
  {
    id: 6013,
    name: 'tavený sýr trojúhelník',
    kcal: 270,
    proteins: 12,
    carbohydrates: 4,
    fats: 23,
  },

  // ==================================================
  // 7xxx — bread, crispbread, wraps
  // ==================================================
  {
    id: 7001,
    name: 'kváskový chléb',
    kcal: 240,
    proteins: 8,
    carbohydrates: 46,
    fats: 2,
  },
  {
    id: 7002,
    name: 'knuspi chléb',
    kcal: 360,
    proteins: 10,
    carbohydrates: 70,
    fats: 3,
  },
  {
    id: 7003,
    name: 'rýžové chlebíčky',
    kcal: 387,
    proteins: 8,
    carbohydrates: 82,
    fats: 3,
  },
  {
    id: 7004,
    name: 'celozrnná bagetka',
    kcal: 270,
    proteins: 9,
    carbohydrates: 50,
    fats: 3,
  },
  {
    id: 7005,
    name: 'tortilla',
    kcal: 310,
    proteins: 8,
    carbohydrates: 52,
    fats: 8,
  },
  {
    id: 7006,
    name: 'krekry',
    kcal: 430,
    proteins: 9,
    carbohydrates: 72,
    fats: 12,
  },
  {
    id: 7007,
    name: 'rýžový chlebíček ovocný',
    kcal: 385,
    proteins: 7.5,
    carbohydrates: 82,
    fats: 2.8,
  },
  {
    id: 7008,
    name: 'celozrnný toastový chléb',
    kcal: 250,
    proteins: 9,
    carbohydrates: 44,
    fats: 4,
  },
  {
    id: 7009,
    name: 'knäckebrot',
    kcal: 350,
    proteins: 10,
    carbohydrates: 70,
    fats: 2,
  },
  {
    id: 7010,
    name: 'bílé pečivo (veka/rohlík)',
    kcal: 270,
    proteins: 9,
    carbohydrates: 56,
    fats: 2.5,
  },
  {
    id: 7011,
    name: 'celozrnná bulka',
    kcal: 260,
    proteins: 9,
    carbohydrates: 49,
    fats: 3.5,
  },

  // ==================================================
  // 8xxx — fats, nuts, sweeteners, flavorings
  // ==================================================
  {
    id: 8001,
    name: 'olivový olej',
    kcal: 900,
    proteins: 0,
    carbohydrates: 0,
    fats: 100,
  },
  {
    id: 8002,
    name: 'ořechy mix',
    kcal: 650,
    proteins: 15,
    carbohydrates: 14,
    fats: 60,
  },
  {
    id: 8003,
    name: 'mandle',
    kcal: 579,
    proteins: 21,
    carbohydrates: 22,
    fats: 50,
  },
  {
    id: 8004,
    name: 'med',
    kcal: 304,
    proteins: 0.3,
    carbohydrates: 82,
    fats: 0,
  },
  {
    id: 8005,
    name: 'marmeláda',
    kcal: 250,
    proteins: 0.5,
    carbohydrates: 62,
    fats: 0,
  },
  {
    id: 8006,
    name: 'dresink (jogurtový)',
    kcal: 90,
    proteins: 4,
    carbohydrates: 6,
    fats: 5,
  },
  {
    id: 8007,
    name: 'sezam',
    kcal: 573,
    proteins: 18,
    carbohydrates: 23,
    fats: 50,
  },
  {
    id: 8008,
    name: 'karamelová omáčka',
    kcal: 260,
    proteins: 1,
    carbohydrates: 65,
    fats: 1,
  },
  {
    id: 8009,
    name: 'švestková omáčka',
    kcal: 170,
    proteins: 0.5,
    carbohydrates: 42,
    fats: 0.2,
  },
  {
    id: 8010,
    name: 'pudink hotový (vanilkový)',
    kcal: 95,
    proteins: 3.0,
    carbohydrates: 16.0,
    fats: 2.0,
  },
  {
    id: 8011,
    name: 'ořechy (drcené)',
    kcal: 650,
    proteins: 15,
    carbohydrates: 14,
    fats: 60,
  },
  {
    id: 8012,
    name: 'kukuřičné lupínky',
    kcal: 370,
    proteins: 7,
    carbohydrates: 84,
    fats: 1,
  },

  // ==================================================
  // 9xxx — spices, seasonings, herbs
  // ==================================================
  {
    id: 9001,
    name: 'kari koření',
    kcal: 325,
    proteins: 14,
    carbohydrates: 58,
    fats: 14,
  },
  {
    id: 9002,
    name: 'skořice mletá',
    kcal: 247,
    proteins: 4.0,
    carbohydrates: 81.0,
    fats: 1.2,
  },
  {
    id: 9003,
    name: 'gulášové koření',
    kcal: 300,
    proteins: 12,
    carbohydrates: 50,
    fats: 10,
  },
  {
    id: 9004,
    name: 'kmín',
    kcal: 333,
    proteins: 20,
    carbohydrates: 50,
    fats: 14,
  },
  {
    id: 9005,
    name: 'koriandr (čerstvý)',
    kcal: 23,
    proteins: 2.1,
    carbohydrates: 3.7,
    fats: 0.5,
  },
  {
    id: 9006,
    name: 'bazalka (čerstvá)',
    kcal: 23,
    proteins: 3.2,
    carbohydrates: 2.7,
    fats: 0.6,
  },
  {
    id: 9007,
    name: 'mexické koření',
    kcal: 300,
    proteins: 12,
    carbohydrates: 50,
    fats: 10,
  },
  {
    id: 9008,
    name: 'pažitka',
    kcal: 30,
    proteins: 3.3,
    carbohydrates: 4.4,
    fats: 0.7,
  },
  {
    id: 9010,
    name: 'mletá paprika',
    kcal: 282,
    proteins: 14.1,
    carbohydrates: 54.9,
    fats: 12.9,
  },
  {
    id: 9011,
    name: 'asijská směs koření',
    kcal: 280,
    proteins: 10,
    carbohydrates: 55,
    fats: 6,
  },
];
