export type FoodType = 'breakfast' | 'snack1' | 'lunch' | 'snack2' | 'dinner';

type Ingredients = {
  name: string;
  amount: number;
};

export type Food = {
  id: number;
  title: string;
  type: FoodType;
  calories: number;
  kj: number;
  proteins: number;
  carbohydrates: number;
  fats: number;
  ingredients: Ingredients[];
};

export const foodData: Food[] = [
  {
    id: 1,
    title: 'Granola s jogurtem',
    type: 'breakfast',
    calories: 350,
    kj: 1465,
    proteins: 14,
    carbohydrates: 52,
    fats: 9,
    ingredients: [
      { name: 'granola', amount: 50 },
      { name: 'bílý jogurt 3%', amount: 120 },
      { name: 'med', amount: 10 },
      { name: 'čerstvé ovoce', amount: 50 },
    ],
  },
  {
    id: 2,
    title: 'Brokolicová pomazánka, opečený toast',
    type: 'snack1',
    calories: 190,
    kj: 795,
    proteins: 8,
    carbohydrates: 22,
    fats: 7,
    ingredients: [
      { name: 'vařená brokolice', amount: 70 },
      { name: 'lučina / ricotta', amount: 40 },
      { name: 'česnek', amount: 3 },
      { name: 'celozrnný toast', amount: 35 },
    ],
  },
  {
    id: 3,
    title: 'Vepřový mexický guláš s rýží',
    type: 'lunch',
    calories: 420,
    kj: 1760,
    proteins: 30,
    carbohydrates: 45,
    fats: 12,
    ingredients: [
      { name: 'vepřové maso (kýta)', amount: 120 },
      { name: 'paprika', amount: 60 },
      { name: 'cibule', amount: 40 },
      { name: 'rajčatový základ', amount: 80 },
      { name: 'mexické koření', amount: 5 },
      { name: 'rýže (vařená)', amount: 150 },
    ],
  },
  {
    id: 4,
    title: 'Obložené knuspi',
    type: 'snack2',
    calories: 160,
    kj: 670,
    proteins: 7,
    carbohydrates: 22,
    fats: 4,
    ingredients: [
      { name: 'knuspi plátky', amount: 20 },
      { name: 'cottage / lučina', amount: 40 },
      { name: 'rajčata', amount: 50 },
      { name: 'pažitka', amount: 3 },
    ],
  },
  {
    id: 5,
    title: 'Salát s kuřecími kousky, dresink',
    type: 'dinner',
    calories: 322,
    kj: 1340,
    proteins: 27,
    carbohydrates: 32,
    fats: 6,
    ingredients: [
      { name: 'grilované kuřecí maso', amount: 110 },
      { name: 'ledový salát', amount: 70 },
      { name: 'rajčata', amount: 60 },
      { name: 'okurka', amount: 60 },
      { name: 'jogurtový dresink', amount: 40 },
    ],
  },
  {
    id: 6,
    title: 'Wrap se šunkou a sýrem, zeleninová obloha',
    type: 'breakfast',
    calories: 345,
    kj: 1443,
    proteins: 20,
    carbohydrates: 39,
    fats: 10,
    ingredients: [
      { name: 'pšeničná tortilla', amount: 60 },
      { name: 'šunka', amount: 40 },
      { name: 'sýr plátkový 30%', amount: 25 },
      { name: 'ledový salát', amount: 40 },
      { name: 'rajčata', amount: 50 },
      { name: 'jogurtový dresink', amount: 20 },
    ],
  },
  {
    id: 7,
    title: 'Meruňkový dezert s tvarohem',
    type: 'snack1',
    calories: 185,
    kj: 774,
    proteins: 11,
    carbohydrates: 25,
    fats: 3,
    ingredients: [
      { name: 'nízkotučný tvaroh', amount: 80 },
      { name: 'meruňky (kompot nebo čerstvé)', amount: 70 },
      { name: 'med', amount: 8 },
      { name: 'skořice', amount: 1 },
    ],
  },
  {
    id: 8,
    title: 'Hovězí rajská omáčka, celozrnné těstoviny',
    type: 'lunch',
    calories: 435,
    kj: 1820,
    proteins: 29,
    carbohydrates: 55,
    fats: 10,
    ingredients: [
      { name: 'hovězí maso (zadní)', amount: 120 },
      { name: 'rajčatová omáčka', amount: 120 },
      { name: 'celozrnné těstoviny (vařené)', amount: 160 },
      { name: 'koření (bobkový list, nové koření)', amount: 2 },
      { name: 'řepný cukr / náhrada – malé množství', amount: 3 },
    ],
  },
  {
    id: 9,
    title: 'Zeleninový salát s vajíčkem a ořechy',
    type: 'snack2',
    calories: 165,
    kj: 690,
    proteins: 8,
    carbohydrates: 10,
    fats: 9,
    ingredients: [
      { name: 'vařené vejce', amount: 50 },
      { name: 'mix salátů', amount: 60 },
      { name: 'rajčata', amount: 40 },
      { name: 'okurka', amount: 40 },
      { name: 'vlašské ořechy', amount: 10 },
    ],
  },
  {
    id: 10,
    title: 'Tuňákové karbanátky, okurkový salát',
    type: 'dinner',
    calories: 320,
    kj: 1338,
    proteins: 27,
    carbohydrates: 32,
    fats: 8,
    ingredients: [
      { name: 'tuňák ve vlastní šťávě', amount: 110 },
      {
        name: 'bramborová směs do karbanátků (vařené brambory)',
        amount: 60,
      },
      { name: 'vejce (část do směsi)', amount: 20 },
      { name: 'koření a bylinky', amount: 2 },
      { name: 'okurka', amount: 100 },
      { name: 'lehké zálivkové koření a ocet', amount: 10 },
    ],
  },
  {
    id: 11,
    title: 'Ovesná kaše s ovocem a ořechy',
    type: 'breakfast',
    calories: 360,
    kj: 1508,
    proteins: 12,
    carbohydrates: 50,
    fats: 11,
    ingredients: [
      { name: 'ovesné vločky', amount: 50 },
      { name: 'mléko 1,5%', amount: 150 },
      { name: 'čerstvé ovoce', amount: 60 },
      { name: 'vlašské ořechy', amount: 15 },
      { name: 'med', amount: 10 },
    ],
  },
  {
    id: 12,
    title: 'Zeleninové smoothie s proteinem',
    type: 'snack1',
    calories: 200,
    kj: 837,
    proteins: 18,
    carbohydrates: 22,
    fats: 4,
    ingredients: [
      { name: 'špenát', amount: 50 },
      { name: 'okurka', amount: 60 },
      { name: 'jablko', amount: 80 },
      { name: 'proteinový prášek', amount: 20 },
      { name: 'voda nebo kokosová voda', amount: 150 },
    ],
  },
  {
    id: 13,
    title: 'Pečené kuře s batáty a zeleninou',
    type: 'lunch',
    calories: 450,
    kj: 1884,
    proteins: 35,
    carbohydrates: 40,
    fats: 12,
    ingredients: [
      { name: 'kuřecí prsa', amount: 130 },
      { name: 'batáty', amount: 150 },
      { name: 'brokolice', amount: 80 },
      { name: 'mrkev', amount: 60 },
      { name: 'olivový olej', amount: 10 },
      { name: 'koření a bylinky', amount: 3 },
    ],
  },
  {
    id: 14,
    title: 'Cottage s čerstvou zeleninou a celozrnným chlebem',
    type: 'snack2',
    calories: 170,
    kj: 711,
    proteins: 12,
    carbohydrates: 20,
    fats: 4,
    ingredients: [
      { name: 'cottage sýr', amount: 100 },
      { name: 'okurka', amount: 50 },
      { name: 'rajčata', amount: 50 },
      { name: 'celozrnný chléb', amount: 30 },
    ],
  },
  {
    id: 15,
    title: 'Losos na grilu s quinoou a zeleninou',
    type: 'dinner',
    calories: 340,
    kj: 1423,
    proteins: 30,
    carbohydrates: 28,
    fats: 10,
    ingredients: [
      { name: 'losos', amount: 120 },
      { name: 'quinoa (vařená)', amount: 100 },
      { name: 'špenát', amount: 60 },
      { name: 'cherry rajčata', amount: 50 },
      { name: 'olivový olej', amount: 10 },
      { name: 'citronová šťáva a bylinky', amount: 3 },
    ],
  },
  {
    id: 16,
    title: 'Proteinová tyčinka a ovoce',
    type: 'snack1',
    calories: 210,
    kj: 880,
    proteins: 20,
    carbohydrates: 25,
    fats: 5,
    ingredients: [
      { name: 'proteinová tyčinka', amount: 60 },
      { name: 'jablko / banán', amount: 100 },
    ],
  },
  {
    id: 17,
    title: 'Zeleninové rizoto s parmazánem',
    type: 'lunch',
    calories: 400,
    kj: 1674,
    proteins: 15,
    carbohydrates: 55,
    fats: 8,
    ingredients: [
      { name: 'rýže (vařená)', amount: 150 },
      { name: 'cuketa', amount: 60 },
      { name: 'paprika', amount: 60 },
      { name: 'hrášek', amount: 50 },
      { name: 'parmazán', amount: 20 },
      { name: 'zeleninový vývar a koření', amount: 5 },
    ],
  },
  {
    id: 18,
    title: 'Řecký jogurt s medem a ořechy',
    type: 'snack2',
    calories: 180,
    kj: 753,
    proteins: 10,
    carbohydrates: 20,
    fats: 6,
    ingredients: [
      { name: 'řecký jogurt 5%', amount: 120 },
      { name: 'med', amount: 10 },
      { name: 'vlašské ořechy', amount: 15 },
    ],
  },
  {
    id: 19,
    title: 'Krůtí steak s pečenými bramborami a zeleninou',
    type: 'dinner',
    calories: 360,
    kj: 1508,
    proteins: 40,
    carbohydrates: 30,
    fats: 6,
    ingredients: [
      { name: 'krůtí prsa', amount: 130 },
      { name: 'brambory', amount: 150 },
      { name: 'zelené fazolky', amount: 80 },
      { name: 'mrkev', amount: 60 },
      { name: 'olivový olej', amount: 10 },
      { name: 'koření a bylinky', amount: 3 },
    ],
  },
  {
    id: 20,
    title: 'Smoothie bowl s ovocem a semínky',
    type: 'breakfast',
    calories: 330,
    kj: 1380,
    proteins: 15,
    carbohydrates: 45,
    fats: 9,
    ingredients: [
      { name: 'banán', amount: 100 },
      { name: 'lesní ovoce (čerstvé nebo mražené)', amount: 80 },
      { name: 'řecký jogurt 5%', amount: 100 },
      { name: 'chia semínka', amount: 15 },
      { name: 'mandlové mléko', amount: 100 },
    ],
  },
];
